### ISSUE TITLE
Github.io pages 404

### ISSUE THREAD

**Issue by elizabethshirley** [Copilot-Language/copilot-language.github.io#25]
I was trying to access the https://copilot-language.github.io/ page, and it seems to be 404

**Comment by fdedden** [comment]
Hi Alex, thank you for letting us know. I will take a look into it.

**Comment by fdedden** [comment]
For whatever reason, it doesn't follow the `index.html` symlink anymore. The site is still there when visting [https://copilot-language.github.io/index.html](https://copilot-language.github.io/index.html). I can only assume they changed something over at Github. Maybe @ivanperez-keera has an idea?

**Comment by fdedden** [comment]
It is working again now, not entirely sure why though. I will close the issue, until further problems arise.
