### ISSUE TITLE
Alternative installation talks about a non existing make file

### ISSUE THREAD

**Issue by chriz-zeller** [Copilot-Language/copilot-language.github.io#9]
The [alternative installation in the index.md](https://github.com/Copilot-Language/copilot-language.github.io/blob/master/index.md) says the following:
```
git clone --recursive https://github.com/Copilot-Language/Copilot.git
cd Copilot
git submodule update --init --remote
make
```
However, the last line doesn't work, because there is no Makefile at `cd Copilot`.

**Comment by chriz-zeller** [comment]
The [Copilot-Readme](https://github.com/Copilot-Language/Copilot/blob/master/README.md) gives a hint that the `make` line might be a `cabal v2-build` (at least for newer cabal versions). See also https://github.com/Copilot-Language/Copilot/issues/40

**Comment by fdedden** [comment]
The website still has an outdated build description, it should be copied over from the Copilot README. The instructions there have been updated as well: Copilot-Language/Copilot#40.
